-- Complete fun facts seed data for all Chicago metro area towns
-- Run this in Supabase SQL Editor

-- Clear existing fun facts
DELETE FROM fun_facts;

-- Insert 3 fun facts for each of the 150+ towns
INSERT INTO fun_facts (town_slug, fact, fact_order) VALUES
  ('chicago', 'Chicago reversed the flow of the Chicago River in 1900, an engineering marvel that made it flow away from Lake Michigan to prevent sewage contamination.', 1),
  ('chicago', 'The world''s first skyscraper was built here in 1885 - the Home Insurance Building stood 10 stories tall and revolutionized urban architecture.', 2),
  ('chicago', 'Deep dish pizza was invented at Pizzeria Uno in 1943, and Chicago-style hot dogs have a strict "no ketchup" rule that locals take very seriously.', 3),
  ('aurora', 'Aurora was one of the first cities in America to use electric streetlights in 1881, earning it the nickname "City of Lights" decades before Las Vegas.', 1),
  ('aurora', 'The Hollywood Casino Aurora is housed in a riverboat on the Fox River, continuing the city''s long riverboat tradition dating back to the 1800s.', 2),
  ('aurora', 'Wayne''s World fans know Aurora as the hometown of Wayne and Garth, and the city has embraced this pop culture connection with local tours.', 3),
  ('naperville', 'Naperville consistently ranks among America''s safest and wealthiest cities, and was named the #1 place to raise children in the U.S. by Bloomberg.', 1),
  ('naperville', 'The Naperville Riverwalk, built in 1981 for the city''s sesquicentennial, features beautiful brick paths, bridges, and fountains along the DuPage River.', 2),
  ('naperville', 'Naper Settlement is a 12-acre outdoor history museum with 30 historic buildings that recreate life in 19th century Illinois.', 3),
  ('joliet', 'Joliet Prison, which opened in 1858, was featured in The Blues Brothers movie and the TV show Prison Break before closing in 2002.', 1),
  ('joliet', 'The Rialto Square Theatre, built in 1926, is called the "Jewel of Joliet" and features stunning architecture that rivals any theater in Chicago.', 2),
  ('joliet', 'Route 66 runs right through downtown Joliet, and the city celebrates its heritage as one of the most iconic stops on the Mother Road.', 3),
  ('elgin', 'The Elgin Watch Company, founded in 1864, produced over 60 million pocket watches and wristwatches before closing in 1968.', 1),
  ('elgin', 'Elgin is home to the largest municipal park district in Illinois, with over 100 parks covering more than 1,800 acres.', 2),
  ('elgin', 'The Grand Victoria Casino was one of Illinois'' first riverboat casinos when it opened in 1994 on the Fox River.', 3),
  ('rockford', 'Rockford once manufactured more furniture than any other city in the U.S., earning the nickname "Forest City" for its woodworking industry.', 1),
  ('rockford', 'Cheap Trick, the legendary rock band, was formed in Rockford in 1973 and still calls the city home.', 2),
  ('rockford', 'The Coronado Theatre, built in 1927, is one of America''s most atmospheric theaters with a stunning Spanish Revival interior.', 3),
  ('waukegan', 'Author Ray Bradbury grew up in Waukegan and immortalized it as "Green Town" in his novels Dandelion Wine and Something Wicked This Way Comes.', 1),
  ('waukegan', 'Jack Benny, one of America''s most beloved comedians, was born in Waukegan in 1894 and frequently mentioned the city in his routines.', 2),
  ('waukegan', 'Waukegan Harbor on Lake Michigan is one of the largest marinas in the Great Lakes, accommodating over 1,000 boats.', 3),
  ('cicero', 'Al Capone made Cicero his headquarters in the 1920s, and the town was effectively controlled by his crime syndicate during Prohibition.', 1),
  ('cicero', 'Cicero is one of the most densely populated towns in America, with a vibrant Latino community making up over 85% of residents.', 2),
  ('cicero', 'Hawthorne Race Course, opened in 1891, is one of the oldest horse racing tracks in the Chicago area and still operates today.', 3),
  ('arlingtonheights', 'Arlington International Racecourse, which opened in 1927, hosted the prestigious Arlington Million and was considered one of the world''s finest horse racing venues until closing in 2021.', 1),
  ('arlingtonheights', 'The Arlington Heights Memorial Library is consistently ranked among the best libraries in the nation for its innovative programs and stunning modern architecture.', 2),
  ('arlingtonheights', 'The Chicago Bears announced plans in 2021 to potentially move to Arlington Heights, purchasing the former Arlington Park racetrack property.', 3),
  ('evanston', 'Northwestern University, founded in 1851, dominates Evanston and is one of the nation''s premier research universities.', 1),
  ('evanston', 'The Woman''s Christian Temperance Union was founded in Evanston in 1874, making the city a center of the prohibition movement.', 2),
  ('evanston', 'Evanston was one of the first cities in the U.S. to offer reparations to Black residents for historical discrimination and redlining.', 3),
  ('schaumburg', 'Woodfield Mall in Schaumburg was the largest shopping mall in the United States when it opened in 1971 and remains one of the biggest.', 1),
  ('schaumburg', 'The village was incorporated in 1956 and transformed from a rural farming community to a major commercial hub in just a few decades.', 2),
  ('schaumburg', 'Medieval Times Dinner & Tournament has been entertaining guests with jousting knights and four-course feasts in Schaumburg since 1991.', 3),
  ('palatine', 'Palatine was named after Palatine, New York, by early settler Joel Wood, who arrived in 1836.', 1),
  ('palatine', 'The historic downtown area features the Clayson House, an 1873 Victorian mansion that serves as a museum and event space.', 2),
  ('palatine', 'Harper College, founded in 1965, serves over 25,000 students and is one of the largest community colleges in Illinois.', 3),
  ('skokie', 'The Illinois Holocaust Museum & Education Center in Skokie is a powerful memorial built after neo-Nazis attempted to march through the predominantly Jewish suburb in 1977.', 1),
  ('skokie', 'Skokie has one of the highest percentages of foreign-born residents in Illinois, creating an incredibly diverse community with over 90 languages spoken.', 2),
  ('skokie', 'The North Shore Channel Aquatic Center features a huge outdoor water park and is a summer destination for families across the region.', 3),
  ('desplaines', 'The first McDonald''s franchise, opened by Ray Kroc in 1955, was located in Des Plaines and is now a museum.', 1),
  ('desplaines', 'The Des Plaines River, which flows through the city, was used by Native Americans and early French explorers as a major transportation route.', 2),
  ('desplaines', 'O''Hare International Airport is partially located in Des Plaines, making it a major economic driver for the city.', 3),
  ('orlandpark', 'Orland Square Mall is one of the most successful shopping centers in the Chicago area, drawing millions of visitors annually.', 1),
  ('orlandpark', 'The Orland Park Prairie is a 28-acre nature preserve that showcases the native tallgrass prairie ecosystem once common in Illinois.', 2),
  ('orlandpark', 'The village has transformed from a small farming community to one of the most affluent suburbs in the southwest Chicago area.', 3),
  ('bolingbrook', 'The Bolingbrook Golf Club hosted LPGA Tour events and is one of the premier public golf courses in the Chicago area.', 1),
  ('bolingbrook', 'The Promenade Bolingbrook is a massive outdoor lifestyle center featuring over 120 stores and restaurants.', 2),
  ('bolingbrook', 'Bolingbrook was one of the fastest-growing communities in America during the 1990s and 2000s, transforming from farmland to a thriving suburb.', 3),
  ('tinleypark', 'The Hollywood Casino Amphitheatre (formerly Tweeter Center) is one of Chicago''s premier outdoor concert venues, hosting major touring acts since 1990.', 1),
  ('tinleypark', 'Tinley Park hosts one of the largest Irish parades in the Chicago area each March, celebrating the community''s strong Irish heritage.', 2),
  ('tinleypark', 'The Oak Park Avenue Metra station is one of the busiest commuter rail stops in the south suburbs.', 3),
  ('oaklawn', 'The village was the site of a major F4 tornado on April 21, 1967, which killed 33 people and remains one of the deadliest tornadoes in Illinois history.', 1),
  ('oaklawn', 'Oak Lawn Community High School has produced several notable athletes, including NBA players and Olympic competitors.', 2),
  ('oaklawn', 'The Oak Lawn Park District manages over 300 acres of parks and recreational facilities throughout the village.', 3),
  ('berwyn', 'The Spindle, a famous roadside sculpture featuring eight cars impaled on a 50-foot spike, stood in Berwyn from 1989 to 2008 and appeared in Wayne''s World.', 1),
  ('berwyn', 'Berwyn has one of the largest Czech populations in America, and the city celebrates its heritage with annual festivals and cultural events.', 2),
  ('berwyn', 'The city is home to the world''s largest laundromat, the Berwyn Laundry, which features over 300 washers and dryers.', 3),
  ('mountprospect', 'Randhurst Village, built on the site of the former Randhurst Mall (opened in 1962), represents a modern transformation from enclosed mall to outdoor lifestyle center.', 1),
  ('mountprospect', 'The Mount Prospect Historical Society maintains the Dietrich Friedrichs House, an 1870s farmhouse that showcases pioneer life.', 2),
  ('mountprospect', 'The village''s extensive bike trail network connects to regional paths, offering over 25 miles of dedicated cycling routes.', 3),
  ('wheaton', 'Wheaton College, founded in 1860, is one of America''s most prestigious Christian liberal arts colleges and Billy Graham''s alma mater.', 1),
  ('wheaton', 'The DuPage County Courthouse in downtown Wheaton has served as the county seat since 1868.', 2),
  ('wheaton', 'Cantigny Park, the former estate of Chicago Tribune publisher Robert McCormick, features beautiful gardens, museums, and a golf course on 500 acres.', 3),
  ('hoffmanestates', 'The Sears Centre Arena (now Now Arena) opened in 2006 and hosts concerts, sporting events, and the Chicago Wolves minor league hockey team.', 1),
  ('hoffmanestates', 'The village is home to the corporate headquarters of Sears Holdings (though Sears has since left) and several other major corporations.', 2),
  ('hoffmanestates', 'The Poplar Creek Music Theater was a popular outdoor concert venue from 1980 to 1994, hosting legendary acts like Pink Floyd and the Grateful Dead.', 3),
  ('oakpark', 'Ernest Hemingway was born in Oak Park in 1899, and his birthplace home is now a museum dedicated to the Nobel Prize-winning author.', 1),
  ('oakpark', 'Frank Lloyd Wright lived and worked in Oak Park for 20 years, and the suburb boasts the largest concentration of Wright-designed buildings in the world.', 2),
  ('oakpark', 'Oak Park became one of the first racially integrated suburbs in America, intentionally promoting diversity during the civil rights era.', 3),
  ('downersgrove', 'The Tivoli Theatre, built in 1928, is one of the few remaining atmospheric theaters in the area and still shows first-run movies.', 1),
  ('downersgrove', 'Downers Grove was named after Pierce Downer, who settled here in 1832 and built the first tavern in the area.', 2),
  ('downersgrove', 'The town is home to the headquarters of DevryEducation Group, Dover Corporation, and several other Fortune 500 companies.', 3),
  ('elmhurst', 'Elmhurst University, founded in 1871, is one of the oldest institutions of higher learning in the Chicago area.', 1),
  ('elmhurst', 'The Elmhurst Art Museum showcases contemporary art and is housed in a building that includes a Mies van der Rohe-designed McCormick House.', 2),
  ('elmhurst', 'York Theatre, built in 1924, is a beautifully restored venue showing classic and contemporary films in a historic setting.', 3),
  ('glenview', 'Naval Air Station Glenview operated from 1937 to 1995 and was a major naval aviation training facility during World War II.', 1),
  ('glenview', 'The Glen Town Center was built on the former naval base property and is now a thriving mixed-use development.', 2),
  ('glenview', 'The Kohl Children''s Museum offers interactive exhibits and has been a favorite destination for young children since 1985.', 3),
  ('buffalogrove', 'The village was named after a grove of trees where buffalo were once spotted grazing in the 1830s.', 1),
  ('buffalogrove', 'Buffalo Grove is known for its excellent schools and has been ranked among the best places to raise a family in Illinois.', 2),
  ('buffalogrove', 'The Arboretum of South Barrington, partly in Buffalo Grove, features extensive gardens and walking trails across 400 acres.', 3),
  ('lombard', 'Lilacia Park hosts an annual Lilac Festival each May, showcasing over 700 lilac bushes and 40,000 tulips in a spectacular floral display.', 1),
  ('lombard', 'The York Theatre, built in 1924, has been beautifully restored and is one of the finest examples of atmospheric theater architecture.', 2),
  ('lombard', 'Lombard was home to legendary NFL coach George Halas, founder of the Chicago Bears, who lived here for many years.', 3),
  ('carolstream', 'Carol Stream was named after the developer''s daughter, Carol, and a stream that ran through the property when it was incorporated in 1959.', 1),
  ('carolstream', 'Wheaton College''s graduate school campus is located in Carol Stream, bringing students and academic programs to the community.', 2),
  ('carolstream', 'The village is home to the headquarters of Christianity Today and several other Christian publishing organizations.', 3),
  ('streamwood', 'The village was incorporated in 1957 and grew rapidly from a population of just 63 to over 40,000 today.', 1),
  ('streamwood', 'Park Place Entertainment Center offers bowling, laser tag, arcade games, and mini-golf, making it a popular family destination.', 2),
  ('streamwood', 'The Streamwood Park District manages over 350 acres of parks, including the popular Poplar Creek Country Club.', 3),
  ('hanoverpark', 'The village was incorporated in 1958 and transformed from farmland to a diverse suburban community in just a few decades.', 1),
  ('hanoverpark', 'The Hanover Park Park District features the Community Center with a state-of-the-art fitness facility and indoor pool.', 2),
  ('hanoverpark', 'The village has one of the most diverse populations in Illinois, with over 50% of residents speaking a language other than English at home.', 3),
  ('bartlett', 'The Bartlett Aquatic Center features water slides, a lazy river, and is one of the most popular summer destinations in the northwest suburbs.', 1),
  ('bartlett', 'The village was originally a stop on the railroad line and grew from a small farming community to a thriving suburb.', 2),
  ('bartlett', 'Bartlett''s Japanese Garden at the Parks District is a peaceful oasis featuring traditional design elements and koi ponds.', 3),
  ('crystallake', 'Crystal Lake is the largest city in McHenry County and derives its name from the beautiful lake at the center of the community.', 1),
  ('crystallake', 'The Raue Center for the Arts, housed in a beautifully restored 1929 vaudeville theater, brings world-class performances to the area.', 2),
  ('crystallake', 'The city hosts the Crystal Lake Independence Day parade, one of the largest July 4th celebrations in the Chicago suburbs.', 3),
  ('addison', 'The Army Trail, a major east-west road, was originally a Native American trail that later became a military road during the Black Hawk War.', 1),
  ('addison', 'The Addison Airport is one of the busiest general aviation airports in the country, serving private aircraft and corporate jets.', 2),
  ('addison', 'The village hosts Taste of Addison, one of the largest food festivals in the Midwest, attracting over 200,000 visitors each June.', 3),
  ('carpentersville', 'The Meadowdale Shopping Center was one of the first shopping centers in the Chicago area when it opened in the 1950s.', 1),
  ('carpentersville', 'The village is divided by the Fox River, with bridges connecting the east and west sides of the community.', 2),
  ('carpentersville', 'Angelo Carpentieri founded the village in the 1800s and built a dam on the Fox River to power his mills.', 3),
  ('plainfield', 'The Plainfield Tornado of 1990 was an F5 tornado that killed 29 people and is one of the most devastating tornadoes in Illinois history.', 1),
  ('plainfield', 'The village has grown exponentially since the 1990s, transforming from a small town to one of the largest communities in Will County.', 2),
  ('plainfield', 'Fort Beggs was a historic fort built during the Black Hawk War, and the area''s history is preserved at the Plainfield Historical Society.', 3),
  ('romeoville', 'The village is home to Lewis University, a Catholic university founded in 1932 by the De La Salle Christian Brothers.', 1),
  ('romeoville', 'The Isle a la Cache Museum sits on an island in the Des Plaines River and recreates a 1750s French fur trading post.', 2),
  ('romeoville', 'Romeoville was incorporated in 1960 and has grown into a major distribution hub with large warehouses and logistics centers.', 3),
  ('woodridge', 'Woodridge was incorporated in 1959 and was one of the first planned communities in the Chicago area.', 1),
  ('woodridge', 'The Cypress Cove Family Aquatic Park features water slides, a lazy river, and interactive play areas for children.', 2),
  ('woodridge', 'The village is home to the Seven Bridges Ice Arena, which offers public skating and hockey programs year-round.', 3),
  ('glendaleheights', 'Camera Park features one of the largest outdoor ice skating rinks in the Chicago area during winter months.', 1),
  ('glendaleheights', 'The village was incorporated in 1959 and grew rapidly during the suburban expansion of the 1960s and 1970s.', 2),
  ('glendaleheights', 'The Glendale Lakes Golf Club is a popular 18-hole public course that attracts golfers from across the region.', 3),
  ('parkridge', 'Park Ridge is the hometown of former Secretary of State Hillary Clinton, who grew up in the suburb during the 1950s and 1960s.', 1),
  ('parkridge', 'The Pickwick Theatre, built in 1928, is an Art Deco masterpiece that still shows movies and hosts live performances.', 2),
  ('parkridge', 'The city is home to Maine South High School, which has one of the most successful high school football programs in Illinois.', 3),
  ('calumetcity', 'Calumet City was known as "Sin City" during the mid-20th century for its numerous nightclubs, strip clubs, and bars that attracted visitors from Chicago.', 1),
  ('calumetcity', 'The city is named after the Calumet region, derived from the French word for peace pipe used by Native Americans.', 2),
  ('calumetcity', 'River Oaks Center, opened in 1966, was one of the first enclosed shopping malls in the south suburbs.', 3),
  ('northbrook', 'Northbrook Court is an upscale shopping mall that opened in 1976 and features luxury retailers like Neiman Marcus.', 1),
  ('northbrook', 'The village is home to the headquarters of Crate & Barrel, Allstate Insurance, and other major corporations.', 2),
  ('northbrook', 'The Chicago Botanic Garden, though technically in Glencoe, has a Northbrook mailing address and is one of the area''s premier attractions.', 3),
  ('algonquin', 'The village is named after the Algonquin Native Americans who originally inhabited the area along the Fox River.', 1),
  ('algonquin', 'Algonquin has experienced tremendous growth since the 1990s, transforming from a small river town to a thriving community.', 2),
  ('algonquin', 'The Fox River Trail runs through Algonquin, offering scenic paths for walking, running, and cycling along the waterway.', 3),
  ('wheeling', 'Restaurant Row in Wheeling features one of the highest concentrations of upscale restaurants in the northwest suburbs.', 1),
  ('wheeling', 'The Chevy Chase Country Club, founded in 1926, is one of the oldest and most prestigious golf clubs in the area.', 2),
  ('wheeling', 'Wheeling was originally settled by German immigrants in the 1830s and later became known for its horse racing track.', 3),
  ('lansing', 'The Lan-Oak Park District facilities include one of the largest public swimming pools in the south suburbs.', 1),
  ('lansing', 'Lansing was named after the state capital of Michigan by early settlers from that state in the mid-1800s.', 2),
  ('lansing', 'The village straddles the Illinois-Indiana border and has close ties to communities in both states.', 3),
  ('highlandpark', 'Ravinia Festival, located in Highland Park, is the oldest outdoor music festival in America, hosting concerts since 1904.', 1),
  ('highlandpark', 'The city is home to numerous historic estates and mansions, reflecting its status as one of Chicago''s wealthiest suburbs.', 2),
  ('highlandpark', 'Highland Park High School has produced numerous notable alumni, including actors, athletes, and business leaders.', 3),
  ('mundelein', 'The University of St. Mary of the Lake, a major Catholic seminary, is located in Mundelein and has trained thousands of priests since 1921.', 1),
  ('mundelein', 'The village was originally called Mechanics Grove but was renamed Mundelein in 1925 after Cardinal George Mundelein.', 2),
  ('mundelein', 'Santa''s Village Azoosment Park operated in Mundelein from 1959 to 2006, bringing joy to generations of children.', 3),
  ('chicagoheights', 'Chicago Heights was a major industrial center and railroad hub, earning the nickname "The Crossroads of the Nation."', 1),
  ('chicagoheights', 'The city was heavily influenced by organized crime during Prohibition, with Al Capone operating several illegal breweries here.', 2),
  ('chicagoheights', 'Prairie State College, founded in 1957, serves over 10,000 students and is a key educational institution in the south suburbs.', 3),
  ('niles', 'The Leaning Tower of Niles is a half-size replica of the Leaning Tower of Pisa, built in 1934 and now a beloved local landmark.', 1),
  ('niles', 'Golf Mill Shopping Center, opened in 1960, was one of the first major shopping centers in the northwest suburbs.', 2),
  ('niles', 'The village has one of the largest Polish populations in Illinois, with vibrant cultural organizations and authentic restaurants.', 3),
  ('lakezurich', 'The village surrounds Lake Zurich, a 235-acre natural lake that provides recreation and defines the community''s character.', 1),
  ('lakezurich', 'The Lake Zurich area was originally settled by German immigrants in the 1830s who named it after Lake Zurich in Switzerland.', 2),
  ('lakezurich', 'The downtown area has been revitalized in recent years with new restaurants, shops, and entertainment venues.', 3),
  ('huntley', 'Huntley experienced explosive growth in the 2000s, transforming from a small farming village to a major residential community.', 1),
  ('huntley', 'The Sun City Huntley development is a large active adult community that has attracted thousands of retirees to the area.', 2),
  ('huntley', 'The village hosts an annual summer fest that draws thousands of visitors for rides, food, and entertainment.', 3),
  ('gurnee', 'Six Flags Great America theme park in Gurnee is one of the most visited attractions in Illinois, drawing millions annually since 1976.', 1),
  ('gurnee', 'Gurnee Mills is one of the largest outlet malls in the Midwest, featuring over 200 stores in a massive indoor complex.', 2),
  ('gurnee', 'KeyLime Cove, a large indoor water park resort, operated in Gurnee from 2008 to 2017 and is now Great Wolf Lodge.', 3),
  ('northchicago', 'Naval Station Great Lakes, the Navy''s largest training installation, is located in North Chicago and trains all enlisted sailors.', 1),
  ('northchicago', 'The Rosalind Franklin University of Medicine and Science is a major medical education institution in North Chicago.', 2),
  ('northchicago', 'The city has a rich industrial history, with companies like Abbott Laboratories maintaining a significant presence here.', 3),
  ('vernonhills', 'The Cuneo Mansion and Gardens, a 1914 Italian Renaissance-style estate, is now a museum and popular wedding venue.', 1),
  ('vernonhills', 'Hawthorn Mall opened in 1973 and has been a major shopping destination for Lake County residents for decades.', 2),
  ('vernonhills', 'Vernon Hills was primarily farmland until the 1960s when developers began transforming it into a planned community.', 3),
  ('newlenox', 'The village has grown tremendously since the 1980s, becoming one of the most desirable communities in southwest Will County.', 1),
  ('newlenox', 'The historic Ganeer Farmhouse, built in the 1870s, is preserved by the New Lenox Area Historical Society.', 2),
  ('newlenox', 'New Lenox is home to numerous parks and forest preserves, offering residents abundant outdoor recreation opportunities.', 3),
  ('glenellyn', 'Lake Ellyn is a beautiful 8.5-acre lake in the heart of downtown, serving as the centerpiece for community gatherings and events.', 1),
  ('glenellyn', 'The College of DuPage, one of the largest community colleges in the U.S., is located in Glen Ellyn and serves over 25,000 students.', 2),
  ('glenellyn', 'Stacy''s Tavern Museum, built in 1846, is a restored stagecoach inn that showcases pioneer life along the old Chicago-to-Galena road.', 3),
  ('oswego', 'Oswego has been one of the fastest-growing communities in Illinois, with its population increasing over 400% since 2000.', 1),
  ('oswego', 'The Hudson Crossing Park features splash pads, playgrounds, and is a popular gathering spot for families.', 2),
  ('oswego', 'The village sits along the Fox River, providing scenic beauty and recreational opportunities for boating and fishing.', 3),
  ('yorkville', 'The United City of Yorkville was formed in 1957 when Bristol and Yorkville merged to create a single municipality.', 1),
  ('yorkville', 'The Raging Waves waterpark is Illinois'' largest outdoor waterpark, featuring massive slides and wave pools.', 2),
  ('yorkville', 'The Fox River flows through Yorkville, and the historic dam and bridges are iconic features of the downtown area.', 3),
  ('lockport', 'The Illinois & Michigan Canal, which runs through Lockport, was a crucial waterway that connected the Great Lakes to the Mississippi River starting in 1848.', 1),
  ('lockport', 'The Gaylord Building, constructed in 1838, is one of the oldest commercial buildings in Illinois and now houses a museum.', 2),
  ('lockport', 'Lockport was named because of the series of locks built to navigate the elevation changes along the I&M Canal.', 3),
  ('westmont', 'Ty Warner Park features beautiful gardens, walking paths, and a community center funded by the Beanie Babies creator.', 1),
  ('westmont', 'The village is home to a thriving downtown with diverse restaurants and shops along Cass Avenue.', 2),
  ('westmont', 'Westmont was incorporated in 1921 and grew rapidly after World War II with the suburban expansion.', 3),
  ('batavia', 'Fermilab, one of the world''s premier particle physics laboratories, is located just outside Batavia and features a massive accelerator ring.', 1),
  ('batavia', 'The Batavia Windmill is a restored Dutch windmill built in 1896 and is now a beloved landmark and symbol of the city.', 2),
  ('batavia', 'The city hosts the Windmill City Festival each summer, celebrating Batavia''s history and community spirit.', 3),
  ('grayslake', 'The College of Lake County''s main campus is located in Grayslake, serving over 15,000 students from across the region.', 1),
  ('grayslake', 'Central Park features a beautiful gazebo, walking paths, and hosts concerts and events throughout the summer.', 2),
  ('grayslake', 'The village was named after founder William Gray, who operated a trading post and tavern here in the 1830s.', 3),
  ('lisle', 'The Morton Arboretum, located partially in Lisle, is a world-renowned outdoor museum featuring 1,700 acres of trees and plants.', 1),
  ('lisle', 'The Benedictine University campus in Lisle has been an educational institution since 1887.', 2),
  ('lisle', 'The Museums at Lisle Station Park preserve local history in restored historic buildings including a train depot.', 3),
  ('bloomingdale', 'The Old Town area features shops and restaurants in a charming historic district along Lake Street.', 1),
  ('bloomingdale', 'Stratford Square Mall opened in 1981 and has been a major retail destination for the northwest suburbs.', 2),
  ('bloomingdale', 'The village was incorporated in 1889 and was primarily agricultural until suburban development began in the 1960s.', 3),
  ('villapark', 'The Illinois Prairie Path, a 61-mile rail-to-trail conversion, has its eastern terminus in Villa Park.', 1),
  ('villapark', 'Villa Park has maintained its charming downtown village center with local shops and restaurants.', 2),
  ('villapark', 'Ovaltine, the chocolate malt drink, was manufactured in Villa Park for decades at the Wander Company factory.', 3),
  ('stcharles', 'The St. Charles Scarecrow Festival is one of the largest and most beloved fall festivals in Illinois, attracting over 100,000 visitors.', 1),
  ('stcharles', 'The historic Hotel Baker, built in 1928, overlooks the Fox River and is a stunning example of Spanish Colonial Revival architecture.', 2),
  ('stcharles', 'The Arcada Theatre, built in 1926, is one of the last remaining atmospheric theaters and hosts concerts and classic films.', 3),
  ('roselle', 'The Roselle Park District operates the Centennial Aquatic Center, featuring pools, slides, and recreation facilities.', 1),
  ('roselle', 'Lake Park is the centerpiece of the village, offering fishing, walking paths, and beautiful natural scenery.', 2),
  ('roselle', 'The village was incorporated in 1922 and has grown from a small farming community to a thriving suburb.', 3),
  ('dolton', 'Dolton was incorporated in 1892 and is one of the older communities in the south suburbs.', 1),
  ('dolton', 'The village is working to revitalize its downtown area along Sibley Boulevard with new businesses and development.', 2),
  ('dolton', 'Dolton is strategically located near major highways and rail lines, making it an important transportation hub.', 3),
  ('darien', 'Waterfall Glen Forest Preserve surrounds much of Darien, offering over 2,500 acres of nature trails and recreation.', 1),
  ('darien', 'The village was incorporated in 1969, making it one of the newer municipalities in DuPage County.', 2),
  ('darien', 'Darien has maintained a strong sense of community with numerous parks and family-friendly events throughout the year.', 3),
  ('zion', 'Zion was founded in 1901 by John Alexander Dowie as a planned Christian community, with streets laid out in a unique spoke pattern.', 1),
  ('zion', 'Illinois Beach State Park, located along Lake Michigan, offers over 4,000 acres of beaches, dunes, and wetlands.', 2),
  ('zion', 'The abandoned Zion Nuclear Power Station operated from 1973 to 1998 and is currently being decommissioned.', 3),
  ('flossmoor', 'Flossmoor is known for its beautiful homes and tree-lined streets, making it one of the most picturesque suburbs in the area.', 1),
  ('flossmoor', 'The Flossmoor Country Club, founded in 1899, is one of the oldest golf clubs in the Chicago area.', 2),
  ('flossmoor', 'Homewood-Flossmoor High School is renowned for its academic excellence and championship athletics programs.', 3),
  ('melrosepark', 'Kiddieland Amusement Park operated in Melrose Park from 1929 to 2009, entertaining generations of Chicago-area families.', 1),
  ('melrosepark', 'The village has a large Italian-American community and is home to numerous authentic Italian restaurants and bakeries.', 2),
  ('melrosepark', 'The Shrine of Our Lady of Guadalupe is a beautiful Catholic shrine that attracts pilgrims from across the region.', 3),
  ('harvey', 'Harvey was founded in 1890 by Turlington Harvey as a model industrial town for workers at the Pullman company.', 1),
  ('harvey', 'The Dixie Square Mall, abandoned since 1978, was famously featured in the mall chase scene in The Blues Brothers.', 2),
  ('harvey', 'The city has a rich history as a railroad and industrial hub in the south suburbs.', 3),
  ('southelgin', 'The Fox River Trail runs through South Elgin, providing beautiful paths for biking, walking, and enjoying nature.', 1),
  ('southelgin', 'The village was incorporated in 1894 and has maintained a distinct identity from its larger neighbor, Elgin.', 2),
  ('southelgin', 'Panton Mill Park preserves the ruins of a historic mill and offers scenic views of the Fox River.', 3),
  ('roundlakebeach', 'The village has extensive lakefront on Round Lake, providing beach access and water recreation for residents.', 1),
  ('roundlakebeach', 'Round Lake Beach was incorporated in 1969, separating from the original village of Round Lake.', 2),
  ('roundlakebeach', 'The community has grown significantly since the 1980s, transforming from a small resort town to a larger residential suburb.', 3),
  ('cresthill', 'Crest Hill is home to numerous shopping centers and retail developments along Plainfield Road and Route 30.', 1),
  ('cresthill', 'The city was incorporated in 1960 and has grown into a major commercial hub in western Will County.', 2),
  ('cresthill', 'Crest Hill shares borders with Joliet and has become integrated into the greater Joliet metropolitan area.', 3),
  ('maywood', 'Maywood is home to Loyola University Medical Center, one of the premier teaching hospitals in the Chicago area.', 1),
  ('maywood', 'Fred Hampton, the influential Black Panther leader, was from Maywood before his controversial death in 1969.', 2),
  ('maywood', 'The village was incorporated in 1881 and developed as a streetcar suburb with direct rail access to Chicago.', 3),
  ('montgomery', 'The village sits along the Fox River and has preserved much of its small-town character despite recent growth.', 1),
  ('montgomery', 'The annual Settler''s Days festival celebrates the community''s pioneer heritage with parades, carnival rides, and entertainment.', 2),
  ('montgomery', 'Montgomery has numerous forest preserves and parks, offering residents abundant natural space and recreation.', 3),
  ('mokena', 'The village name comes from a Native American word believed to mean "turtle," though the exact origin is debated.', 1),
  ('mokena', 'Downtown Mokena features charming shops and restaurants along Front Street, maintaining a quaint small-town atmosphere.', 2),
  ('mokena', 'The village has grown significantly since the 1980s, transforming from a rural community to a thriving suburb.', 3),
  ('homewood', 'Homewood-Flossmoor High School has one of the most successful boys'' basketball programs in Illinois history.', 1),
  ('homewood', 'The village features a vibrant downtown area with local restaurants, shops, and the historic Irwin Park.', 2),
  ('homewood', 'Art Hoffer Park includes beautiful walking paths, sports facilities, and hosts community events throughout the year.', 3),
  ('homerglen', 'Homer Glen was incorporated in 2001, making it one of the newest municipalities in the Chicago area.', 1),
  ('homerglen', 'The village has preserved much of its rural character with large lot sizes and abundant forest preserve land.', 2),
  ('homerglen', 'Heritage Park features walking trails, fishing ponds, and open space for residents to enjoy nature.', 3),
  ('cary', 'Cary is located along the Fox River and offers beautiful natural scenery and water recreation opportunities.', 1),
  ('cary', 'The village has a charming downtown area along Route 14 with local shops and restaurants.', 2),
  ('cary', 'Three Oaks Recreation Area features sports fields, trails, and is a hub for community activities and youth sports.', 3),
  ('blueisland', 'Blue Island was once an actual island surrounded by swamps and waterways before the area was drained and developed.', 1),
  ('blueisland', 'The city is home to the Blue Island Brewing Company, continuing the area''s long tradition of beer production.', 2),
  ('blueisland', 'The historic Western Avenue District features Victorian-era buildings and hosts the annual Blue Island Historic Home Tour.', 3),
  ('libertyville', 'Lambs Farm, a nonprofit organization serving adults with developmental disabilities, operates a petting zoo, country store, and restaurant in Libertyville.', 1),
  ('libertyville', 'The village has preserved its historic downtown with locally-owned shops and restaurants along Milwaukee Avenue.', 2),
  ('libertyville', 'Cook Memorial Library in Libertyville is a beautiful modern facility that serves as a community gathering space.', 3),
  ('woodstock', 'The Woodstock Square was the filming location for the movie Groundhog Day, and the city celebrates annually with Groundhog Days festival.', 1),
  ('woodstock', 'The historic Woodstock Opera House, built in 1890, hosts theater productions, concerts, and was featured in the Groundhog Day movie.', 2),
  ('woodstock', 'Chester Gould, creator of the Dick Tracy comic strip, lived in Woodstock and the city honors his legacy with a museum.', 3),
  ('northaurora', 'The village is split by the Fox River, with the historic downtown on the east side featuring charming shops and restaurants.', 1),
  ('northaurora', 'Oakhurst Forest Preserve offers hiking trails, picnic areas, and beautiful views of the Fox River valley.', 2),
  ('northaurora', 'North Aurora was primarily agricultural until the 1960s when suburban development began to transform the community.', 3),
  ('frankfort', 'Old Plank Road Trail, a 22-mile rail-to-trail path, runs through Frankfort and is popular for biking and walking.', 1),
  ('frankfort', 'The historic downtown area features 19th-century buildings and has become a destination for antique shopping and dining.', 2),
  ('frankfort', 'Frankfort has maintained its small-town character while growing into one of the most desirable communities in Will County.', 3),
  ('lakeforest', 'Lake Forest is one of Chicago''s wealthiest suburbs, featuring massive estates, private beaches, and the prestigious Lake Forest College.', 1),
  ('lakeforest', 'Market Square, designed by Howard Van Doren Shaw in 1916, was one of America''s first planned shopping centers.', 2),
  ('lakeforest', 'The Deer Path Inn, built in 1929, is a luxury hotel designed to resemble an English country manor.', 3),
  ('burbank', 'Burbank was incorporated in 1970, making it a relatively new municipality despite the area being settled much earlier.', 1),
  ('burbank', 'The city is home to numerous parks including Tobosky Park and Kennedy Park, offering recreation for residents.', 2),
  ('burbank', 'Burbank has maintained a strong working-class community identity while being surrounded by larger suburbs.', 3),
  ('geneva', 'Geneva hosts the Swedish Days festival every June, one of the largest Swedish heritage festivals in the country, celebrating the city''s Scandinavian roots.', 1),
  ('geneva', 'The historic Third Street downtown district features beautiful 19th-century architecture and is filled with shops, restaurants, and galleries.', 2),
  ('geneva', 'The Fox River Trail runs through Geneva, connecting to a regional network of over 40 miles of scenic pathways.', 3),
  ('shorewood', 'The village experienced tremendous growth in the 1990s and 2000s, transforming from farmland to a thriving residential community.', 1),
  ('shorewood', 'Hammel Woods Forest Preserve offers over 500 acres of trails, fishing ponds, and natural habitat along the DuPage River.', 2),
  ('shorewood', 'The village has excellent schools and family-friendly amenities, making it a popular destination for young families.', 3),
  ('westchicago', 'The Kline Creek Farm is a living history museum that recreates an 1890s farmstead with period-authentic buildings and practices.', 1),
  ('westchicago', 'West Chicago was originally called Turner until 1896 when residents voted to change the name to attract more business.', 2),
  ('westchicago', 'The city hosts the annual Railroad Days festival celebrating its heritage as a major rail junction.', 3),
  ('southholland', 'South Holland was settled by Dutch immigrants in the 1840s and 1850s, and the community has maintained strong Dutch cultural traditions.', 1),
  ('southholland', 'The South Suburban College campus is located in South Holland, serving students from across the region.', 2),
  ('southholland', 'The village is known for its well-maintained parks and the popular Bike Path along Thorn Creek.', 3),
  ('warrenville', 'Warrenville Grove Forest Preserve features the historic Julius Warren homestead and beautiful wooded trails along the west branch of the DuPage River.', 1),
  ('warrenville', 'The city is home to Fermilab''s Wilson Hall, the iconic high-rise building housing the particle physics laboratory.', 2),
  ('warrenville', 'Cantera, a large mixed-use development, has transformed part of Warrenville with shops, restaurants, and entertainment venues.', 3),
  ('matteson', 'Matteson was founded by German immigrant Joel Matteson, who became Governor of Illinois from 1853 to 1857.', 1),
  ('matteson', 'Lincoln Mall operated in Matteson from 1973 to 2015 and was a major shopping destination for the south suburbs.', 2),
  ('matteson', 'The village is working to redevelop former retail sites and attract new businesses to the community.', 3),
  ('morris', 'Morris was a critical stop on the Illinois & Michigan Canal and later became an important railroad junction.', 1),
  ('morris', 'The Grundy County Courthouse, built in 1913, is a beautiful example of Classical Revival architecture.', 2),
  ('morris', 'Morris is home to the Dresden Nuclear Power Station, one of the first nuclear plants built in Illinois.', 3),
  ('parkforest', 'Park Forest was planned and built after World War II as one of America''s first post-war planned communities for veterans.', 1),
  ('parkforest', 'The village was designed with a unique town center featuring shops and apartments above retail, predating modern mixed-use development.', 2),
  ('parkforest', 'Illinois Theatre Center in Park Forest has been producing professional theater since 1976.', 3),
  ('lincolnwood', 'Lincolnwood Town Center was one of the first enclosed shopping malls in the Chicago area when it opened in 1959.', 1),
  ('lincolnwood', 'The village has a large Jewish population and is home to numerous synagogues and kosher restaurants.', 2),
  ('lincolnwood', 'The Purple Hotel, a distinctive purple-colored high-rise, was a Lincolnwood landmark from 1960 until its demolition in 2017.', 3),
  ('minooka', 'Aux Sable Aqueduct, built in 1848 as part of the I&M Canal, is a historic stone structure preserved in Minooka.', 1),
  ('minooka', 'The village has experienced rapid growth since 2000, with new residential developments transforming the community.', 2),
  ('minooka', 'The Minooka Park District manages several parks including Veterans Memorial Park with sports facilities and playgrounds.', 3),
  ('rollingmeadows', 'The city was developed in the 1950s as a planned community with curving streets and abundant green space.', 1),
  ('rollingmeadows', 'The Rolling Meadows Community Center features fitness facilities, an indoor pool, and hosts numerous community programs.', 2),
  ('rollingmeadows', 'Ned Brown Preserve (Busse Woods) borders Rolling Meadows and offers over 3,700 acres of forest preserve with trails and a lake.', 3),
  ('bensenville', 'Bensenville is home to significant portions of O''Hare International Airport, including cargo facilities and parking.', 1),
  ('bensenville', 'The village hosts the annual Bensenville Fest, one of the largest street festivals in the northwest suburbs.', 2),
  ('bensenville', 'White Pines Golf Club, designed by Edward Lawrence Packard, is a challenging 18-hole public course in Bensenville.', 3),
  ('wilmette', 'The Baha''i House of Worship in Wilmette is the only Baha''i temple in North America and features stunning architecture and gardens.', 1),
  ('wilmette', 'Gillson Park on Lake Michigan offers a beautiful beach, harbor, and recreational facilities with stunning skyline views.', 2),
  ('wilmette', 'The Plaza del Lago shopping center, built in 1928, was one of the first outdoor shopping centers in America.', 3),
  ('roundlake', 'Round Lake encompasses several small natural lakes that give the community its name and recreational identity.', 1),
  ('roundlake', 'The village was originally founded as a resort community in the late 1800s, attracting Chicago visitors seeking lakeside retreats.', 2),
  ('roundlake', 'Renwick Park features sports fields, trails, and is a central gathering place for community events and activities.', 3),
  ('lemont', 'Lemont is known as the "Quarry Capital of Illinois" because of the extensive limestone quarries that shaped the town''s history.', 1),
  ('lemont', 'The historic I&M Canal runs through Lemont, and the downtown features beautifully preserved 19th-century limestone buildings.', 2),
  ('lemont', 'The Old Quarry Adventures waterpark and adventure park utilizes a former quarry site for swimming and recreation.', 3),
  ('mortongrove', 'The Morton Grove Public Library is consistently ranked among the best libraries in the nation for its services and programs.', 1),
  ('mortongrove', 'The village is home to significant portions of the Chicago Botanic Garden, though it has a Glencoe address.', 2),
  ('mortongrove', 'Morton Grove was one of the first communities in America to ban handgun ownership in 1981, though the law was later repealed.', 3),
  ('richtonpark', 'Richton Park was incorporated in 1926 and developed as a residential community for workers in nearby industrial areas.', 1),
  ('richtonpark', 'The village is working to revitalize its downtown area and attract new development to the community.', 2),
  ('richtonpark', 'Richton Square Mall operated from 1978 to 2002 and was once a major shopping destination for the far south suburbs.', 3),
  ('hickoryhills', 'The village was incorporated in 1951 and developed rapidly during the post-war suburban expansion.', 1),
  ('hickoryhills', 'Hickory Hills has numerous parks including Community Park, which features sports fields and walking paths.', 2),
  ('hickoryhills', 'The village is home to many second and third-generation families who settled here in the 1950s and 1960s.', 3),
  ('bridgeview', 'SeatGeek Stadium (formerly Toyota Park) is home to the Chicago Fire FC soccer team and hosts concerts and events.', 1),
  ('bridgeview', 'The village is located along the Chicago Sanitary and Ship Canal, which was a major engineering achievement when completed in 1900.', 2),
  ('bridgeview', 'Bridgeview has a large Arab-American community, particularly from Palestine, with numerous Middle Eastern restaurants and shops.', 3),
  ('justice', 'The village was incorporated in 1911 and developed as a small residential community between larger suburbs.', 1),
  ('justice', 'Justice is home to several industrial and warehouse facilities along major transportation corridors.', 2),
  ('justice', 'The village maintains a tight-knit community atmosphere despite its industrial character and proximity to major highways.', 3),
  ('coalcity', 'Coal City was named for the extensive coal mining that took place in the area during the 19th and early 20th centuries.', 1),
  ('coalcity', 'The city has a strong agricultural heritage and hosts the annual Coal City Labor Day celebration.', 2),
  ('coalcity', 'The Fossil Rock Park and Playground features unique play equipment shaped like prehistoric creatures, celebrating the area''s fossil finds.', 3),
  ('countryclubhills', 'The village was developed in the 1950s and 1960s as a residential community with tree-lined streets and single-family homes.', 1),
  ('countryclubhills', 'Country Club Hills is home to several parks and recreation facilities managed by the Hills Park District.', 2),
  ('countryclubhills', 'The community has maintained a stable, family-oriented character for over 60 years.', 3),
  ('winnetka', 'The movie Home Alone was filmed in Winnetka, and the famous house is located on Lincoln Avenue.', 1),
  ('winnetka', 'Winnetka is one of Chicago''s wealthiest suburbs, featuring massive estates and homes along the Lake Michigan shoreline.', 2),
  ('winnetka', 'The village has excellent schools and the beautiful Hubbard Woods Park, a centerpiece of the community.', 3),
  ('paloshills', 'The village was incorporated in 1958 and developed on the hilly terrain of the Palos area, giving it its name.', 1),
  ('paloshills', 'The Palos Forest Preserve surrounds much of the village, offering over 14,000 acres of trails and natural beauty.', 2),
  ('paloshills', 'Palos Hills is home to Trinity Christian College, a small private liberal arts college founded in 1959.', 3),
  ('plano', 'Plano was the birthplace of the Plano Harvester, a revolutionary grain harvesting machine invented here in the 1800s.', 1),
  ('plano', 'The Plano Stone Church, built in 1864, is a beautiful historic landmark made from locally quarried limestone.', 2),
  ('plano', 'The city hosts Plano Harvest Days each September, celebrating the agricultural heritage of the community.', 3),
  ('alsip', 'The Alsip-Hazelgreen-Oaklawn Fire District serves the community and is one of the busiest fire departments in the south suburbs.', 1),
  ('alsip', 'The village is home to numerous industrial and commercial businesses along major highways and rail lines.', 2),
  ('alsip', 'Community Park and other recreation areas provide green space and activities for residents in this largely commercial village.', 3),
  ('steger', 'Steger was named after John V. Steger, a piano manufacturer who moved his factory here in 1896 and built housing for workers.', 1),
  ('steger', 'The Steger Piano Company produced over 70,000 pianos before closing during the Great Depression.', 2),
  ('steger', 'The village has preserved several historic buildings from its industrial past along the downtown railroad corridor.', 3),
  ('burrridge', 'Burr Ridge is one of the most affluent suburbs in the Chicago area, featuring large estates on wooded lots.', 1),
  ('burrridge', 'The village name comes from the hilly, wooded terrain that resembles burrs from chestnut trees.', 2),
  ('burrridge', 'Burr Ridge Village Center offers upscale shopping and dining in a beautiful outdoor setting.', 3),
  ('wooddale', 'The village was incorporated in 1924 and developed around the lumber industry that harvested the area''s forests.', 1),
  ('wooddale', 'Wood Dale Grove Forest Preserve offers natural areas and trails right in the heart of the community.', 2),
  ('wooddale', 'The city is conveniently located near O''Hare Airport and major highways, making it a hub for business and industry.', 3),
  ('lakeinthehills', 'The village features numerous lakes and ponds, including the large Lake in the Hills, which give the community its recreational character.', 1),
  ('lakeinthehills', 'The community has grown dramatically since the 1990s, transforming from a small resort area to a major residential suburb.', 2),
  ('lakeinthehills', 'Independence Grove Forest Preserve offers a massive lake for boating, fishing, and a beautiful beach for swimming.', 3),
  ('hinsdale', 'Hinsdale is one of Chicago''s most prestigious suburbs, featuring magnificent homes, upscale shops, and the historic Hinsdale Golf Club.', 1),
  ('hinsdale', 'Katherine Legge Memorial Park features beautiful gardens, walking paths, and the Graue Mill, a historic water-powered gristmill from 1852.', 2),
  ('hinsdale', 'The village has a charming downtown along First Street with boutique shops, fine dining, and a small-town atmosphere.', 3),
  ('midlothian', 'The village was named after the Midlothian region of Scotland by early Scottish settlers in the 1830s.', 1),
  ('midlothian', 'Bachelor''s Grove Cemetery, located in the Rubio Woods Forest Preserve, is considered one of the most haunted places in America.', 2),
  ('midlothian', 'The Midlothian Meadows is a large forest preserve offering trails, fishing, and natural areas for residents to enjoy.', 3),
  ('gary', 'Gary was founded in 1906 by U.S. Steel and was once a thriving steel town, home to the largest integrated steel mill in the world.', 1),
  ('gary', 'Michael Jackson and the Jackson 5 were born and raised in Gary, and the family home is a local landmark.', 2),
  ('gary', 'The City Methodist Church, abandoned since the 1970s, is an iconic ruins that has been featured in numerous films and photography projects.', 3),
  ('merrillville', 'Merrillville is a major commercial hub in northwest Indiana, featuring extensive retail, dining, and entertainment options.', 1),
  ('merrillville', 'Deep River Waterpark, one of the largest waterparks in Indiana, offers slides, pools, and attractions for summer fun.', 2),
  ('merrillville', 'The town developed rapidly in the 1970s and 1980s as retail and business shifted away from downtown Gary.', 3),
  ('hammond', 'Hammond was a major industrial city known for meat packing, with companies like the Hammond Packing Company operating large facilities.', 1),
  ('hammond', 'The Horseshoe Casino Hammond, opened in 1996, was Indiana''s first casino and remains a major entertainment destination.', 2),
  ('hammond', 'The city is named after George Henry Hammond, who invented the refrigerated railroad car in the 1860s.', 3),
  ('crownpoint', 'The Old Lake County Courthouse Square in downtown Crown Point is a beautiful historic district featuring the distinctive courthouse built in 1878.', 1),
  ('crownpoint', 'Crown Point was a popular destination for quickie weddings in the 1930s, with celebrities like Ronald Reagan and Joe DiMaggio marrying here.', 2),
  ('crownpoint', 'The city has preserved its historic downtown while growing into one of the most desirable communities in northwest Indiana.', 3),
  ('hobart', 'Lake George in downtown Hobart is a beautiful glacial lake surrounded by parks, a beach, and the historic Festival Park.', 1),
  ('hobart', 'The Art Theatre, built in 1947, is a beloved Art Deco movie palace that still shows films and hosts events.', 2),
  ('hobart', 'Hobart has maintained a strong community identity while managing significant commercial development along U.S. Route 30.', 3),
  ('schererville', 'Schererville was named after Nicholas Scherer, who opened a tavern here along the Sauk Trail in the 1840s.', 1),
  ('schererville', 'The town has extensive retail and commercial development, particularly along U.S. Route 30, making it a regional shopping destination.', 2),
  ('schererville', 'Redar Park and Pennsy Greenway offer walking trails, sports facilities, and natural areas for recreation.', 3),
  ('munster', 'Community Hospital in Munster is a major medical center serving northwest Indiana and the south Chicago suburbs.', 1),
  ('munster', 'The town was named after the Munster region of Germany by early German and Dutch settlers.', 2),
  ('munster', 'Munster has excellent schools, parks, and a strong sense of community, making it one of the most desirable towns in the region.', 3),
  ('stjohn', 'Lake Central High School in St. John is one of the largest and most successful high schools in Indiana.', 1),
  ('stjohn', 'The town was named after John Hack, founder of the settlement, and "Saint" was added to honor his contributions.', 2),
  ('stjohn', 'St. John has grown dramatically since the 1990s, transforming from a small rural town to a thriving residential community.', 3),
  ('highland', 'Wicker Memorial Park offers over 200 acres of recreation including trails, sports fields, and the beautiful Lincoln Park.', 1),
  ('highland', 'The town has a strong sense of community and hosts numerous events including the Highland Fourth of July celebration.', 2),
  ('highland', 'Highland was settled by Dutch immigrants in the 1840s and 1850s, and the community has maintained cultural traditions.', 3),
  ('eastchicago', 'East Chicago was a major industrial center with steel mills, oil refineries, and chemical plants driving the economy for decades.', 1),
  ('eastchicago', 'The city is home to Indiana Harbor, which was one of the busiest ports on the Great Lakes during the industrial era.', 2),
  ('eastchicago', 'East Chicago faces environmental challenges from its industrial past but is working to remediate contaminated sites and attract new development.', 3),
  ('portage', 'Portage Lakefront and Riverwalk offers beautiful beaches on Lake Michigan, trails, and a pavilion with stunning views.', 1),
  ('portage', 'The city is home to significant portions of the Indiana Dunes National Park, preserving unique dune ecosystems and beaches.', 2),
  ('portage', 'Portage was named for the historic portage route between the Great Lakes and Mississippi River watersheds used by Native Americans and explorers.', 3),
  ('valparaiso', 'Valparaiso University, founded in 1859, is a prestigious Lutheran university with a beautiful campus featuring the iconic Chapel of the Resurrection.', 1),
  ('valparaiso', 'The city hosts the annual Popcorn Festival each September, celebrating Orville Redenbacher, who lived and worked in Valparaiso.', 2),
  ('valparaiso', 'Downtown Valparaiso features a charming courthouse square with locally-owned shops, restaurants, and the historic Memorial Opera House.', 3),
  ('cedarlake', 'Cedar Lake is named after the beautiful 781-acre natural lake at the center of the town, offering swimming, boating, and fishing.', 1),
  ('cedarlake', 'The town was originally developed as a summer resort community for Chicago residents in the late 1800s.', 2),
  ('cedarlake', 'Lemon Lake County Park offers camping, trails, and water recreation, making Cedar Lake a destination for outdoor enthusiasts.', 3),
  ('dyer', 'Dyer was named after Aaron Hart Dyer, who purchased land here in 1857 and was instrumental in bringing the railroad to the area.', 1),
  ('dyer', 'The town has excellent schools and parks, including Pheasant Hills Park with sports facilities and nature areas.', 2),
  ('dyer', 'Dyer has maintained a small-town character while being conveniently located near major highways and Chicago.', 3),
  ('griffith', 'Griffith was named after Benjamin Griffith, who was instrumental in bringing the railroad to the area in the 1890s.', 1),
  ('griffith', 'The town is known for its parks, including Community Park with a beautiful lake, trails, and recreation facilities.', 2),
  ('griffith', 'The Griffith Historical Park & Museum preserves local history with restored buildings and exhibits about the town''s development.', 3),
  ('chesterton', 'The Indiana Dunes National Park headquarters is located in Chesterton, and the town serves as a gateway to the beautiful dunes and beaches.', 1),
  ('chesterton', 'The European Market in downtown Chesterton offers fresh produce, baked goods, and artisan products every Saturday from May through October.', 2),
  ('chesterton', 'Coffeecreek Watershed Preserve features over 500 acres of trails, prairies, and natural areas right in the heart of town.', 3),
  ('lakestation', 'Lake Station was originally called East Gary and later Lake Station because of its location on the railroad near several lakes.', 1),
  ('lakestation', 'The city is home to the Indiana Welcome Center, greeting visitors entering Indiana from Illinois on I-80/94.', 2),
  ('lakestation', 'Lake Station has several parks including Riverview Park with trails along the Little Calumet River.', 3),
  ('lowell', 'Lowell was founded by Melville Halsted in 1853 and named after Lowell, Massachusetts, a major textile manufacturing city.', 1),
  ('lowell', 'The town hosts the annual Lowell Homecoming Festival each summer, celebrating community spirit with a parade, carnival, and events.', 2),
  ('lowell', 'Oak Ridge Prairie County Park near Lowell offers trails, fishing, and natural areas showcasing Indiana''s prairie heritage.', 3),
  ('lagrange', 'La Grange has a charming historic downtown with the La Grange Theatre, built in 1932 and still showing first-run movies.', 1),
  ('lagrange', 'The village was the home of Lyons Township High School, one of the largest and most successful high schools in Illinois.', 2),
  ('lagrange', 'The Stone Avenue train station serves as a busy Metra stop, connecting La Grange residents to downtown Chicago.', 3),
  ('westernsprings', 'Western Springs is known for its beautiful historic homes and tree-lined streets, creating a picturesque small-town atmosphere.', 1),
  ('westernsprings', 'The Grand Avenue Water Tower, built in 1890, is an iconic landmark that symbolizes the village''s history.', 2),
  ('westernsprings', 'Western Springs has an excellent park district with the popular Grand Avenue Community Center and numerous recreational facilities.', 3),
  ('clarendonhills', 'The village has maintained its small-town character with a compact downtown area featuring local shops and restaurants.', 1),
  ('clarendonhills', 'Prospect Park is the centerpiece of the village, offering recreation facilities, a pool, and hosts community events.', 2),
  ('clarendonhills', 'Clarendon Hills is known for its excellent schools and family-friendly atmosphere, making it a highly desirable suburb.', 3),
  ('bellwood', 'Bellwood was an important manufacturing center, with companies like Sunbeam and other industrial firms operating large facilities.', 1),
  ('bellwood', 'The village is working to revitalize its downtown area along Mannheim Road and attract new businesses and development.', 2),
  ('bellwood', 'Bellwood has a diverse population and hosts cultural events celebrating the community''s many ethnic backgrounds.', 3),
  ('brookfield', 'Brookfield Zoo, officially Chicago Zoological Park, opened in 1934 and is one of the largest and most visited zoos in America.', 1),
  ('brookfield', 'The village features beautiful homes from the early 20th century and a charming downtown along Burlington Avenue.', 2),
  ('brookfield', 'Brookfield is bisected by Salt Creek and features several parks and forest preserves along the waterway.', 3),
  ('evergreenpark', 'Evergreen Plaza shopping center, which opened in 1952, was one of the first major outdoor shopping centers in the Chicago area.', 1),
  ('evergreenpark', 'The village has maintained strong community programs and excellent parks, including Yukich Fields with extensive sports facilities.', 2),
  ('evergreenpark', 'Evergreen Park is known for its well-maintained neighborhoods and strong property values in the southwest suburbs.', 3),
  ('oakforest', 'Oak Forest Hospital, now part of the Cook County health system, was established in 1910 as a tuberculosis sanatorium.', 1),
  ('oakforest', 'The city features numerous parks including Yankee Woods Forest Preserve, offering trails and natural areas.', 2),
  ('oakforest', 'Oak Forest has grown from a small village to a significant city in the south suburbs with diverse residential areas.', 3),
  ('palosheights', 'The village sits on the hilly terrain of the Palos area, giving it its name and distinctive topography compared to flat suburbs.', 1),
  ('palosheights', 'Recreation Park and other facilities offer residents sports fields, playgrounds, and green space throughout the village.', 2),
  ('palosheights', 'Palos Heights is surrounded by the Palos Forest Preserve, providing easy access to over 14,000 acres of trails and nature.', 3),
  ('broadview', 'The village was incorporated in 1910 and developed along major railroad lines and industrial corridors.', 1),
  ('broadview', 'Broadview has a diverse population and is working to revitalize its commercial districts and attract new businesses.', 2),
  ('broadview', 'The village maintains several parks and recreation facilities despite its small size and industrial character.', 3),
  ('lyons', 'Lyons was a major industrial center with meat packing plants, including the famous Hofman sausage factory.', 1),
  ('lyons', 'The village is bisected by the Chicago Sanitary and Ship Canal and has numerous historic industrial buildings.', 2),
  ('lyons', 'Hofmann Tower, a distinctive water tower shaped like a beer stein, was an iconic landmark until it was demolished in 1974.', 3),
  ('riverforest', 'Dominican University, founded in 1901, is a Catholic liberal arts university with a beautiful campus in River Forest.', 1),
  ('riverforest', 'The village features numerous homes designed by Frank Lloyd Wright and other Prairie School architects.', 2),
  ('riverforest', 'River Forest has maintained its historic character with preservation ordinances protecting significant buildings and streetscapes.', 3),
  ('riverside', 'Riverside was one of the first planned communities in America, designed by Frederick Law Olmsted and Calvert Vaux in 1869.', 1),
  ('riverside', 'The village features curving streets, riverside parks, and preserved gas lamps that reflect the original Olmsted design.', 2),
  ('riverside', 'The Riverside Historic District is listed on the National Register of Historic Places, preserving the entire village.', 3),
  ('summit', 'Summit was an important railroad junction and industrial center, with the Argo Corn Products Refinery employing thousands.', 1),
  ('summit', 'The village sits along the Chicago Sanitary and Ship Canal and the historic I&M Canal corridor.', 2),
  ('summit', 'The Argo Community High School served the area from 1924 to 1982 and was a center of community life.', 3),
  ('willowsprings', 'Willow Springs is home to the Willowbrook Wildlife Center, a facility that rehabilitates injured and orphaned wild animals.', 1),
  ('willowsprings', 'The village is surrounded by the Palos Forest Preserve and features the historic Palos Trails, popular for hiking and biking.', 2),
  ('willowsprings', 'The small village has maintained a quiet, rural character despite being surrounded by larger suburbs.', 3),
  ('worth', 'The village was incorporated in 1914 and named after Civil War general and railroad executive William Jenkins Worth.', 1),
  ('worth', 'Worth is a small but well-maintained village with several parks and easy access to nearby shopping and entertainment.', 2),
  ('worth', 'The village has maintained stable residential neighborhoods and a strong sense of community for over 100 years.', 3);

-- Verify the data was inserted
SELECT COUNT(*) as total_facts FROM fun_facts;
